# Generated by Django 5.1.2 on 2024-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('number', models.CharField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('region', models.CharField(max_length=254)),
                ('district', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=245, unique=True)),
            ],
            options={
                'ordering': ['name', 'number'],
                'unique_together': {('number', 'name')},
            },
        ),
    ]
