# Generated by Django 5.1.2 on 2024-10-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('question', 'Question'), ('incident', 'Incident'), ('problem', 'Problem')], default='incident', max_length=254)),
                ('priority', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=1, max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open or Pending'), ('closed', 'Closed or Resolved'), ('archive', 'Archive')], default='open', max_length=254)),
                ('description', models.TextField()),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='/downloads')),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to='tickets.centre')),
            ],
            options={
                'ordering': ['subject', 'reported_by'],
                'unique_together': {('reported_by', 'subject')},
            },
        ),
    ]
