# Generated by Django 5.1.2 on 2024-10-30 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
